backups:
  full:
    enabled: true
    debug: true
    schedule: "*/5 * * * *"
  destination: minio://azuregw-minio.minio.svc:9000/dgraph-backups
alpha:
  configFile:
    config.hcl: |
      whitelist = "10.0.0.0/8,172.0.0.0/8,192.168.0.0/16"
      lru_mb    = 2048
