provisionDataStore:
  elasticsearch: true
storage:
  type: elasticsearch
  cassandra:
    user: elasticuser
    usePassword: true
    password: CHANGEME

agent:
  ## Optional Monitoring for Prometheus
  serviceMonitor:
    enabled: false
    additionalLabels: {release:  prometheus}
collector:
  ## Optional Monitoring for Prometheus
  serviceMonitor:
    enabled: false
    additionalLabels: {release:  prometheus}
query:
  ## Optional Monitoring for Prometheus
  serviceMonitor:
    enabled: false
    additionalLabels: {release:  prometheus}
