provisionDataStore:
  cassandra: true
storage:
  type: cassandra
  cassandra:
    user: cassandrauser
    usePassword: true
    password: V8w7V3i7n8h67cHkEXPan8wmYy7ixhFx
    extraEnv:
      ## Change Seed Provider from `org.apache.cassandra.locator.SimpleSeedProvider`
      - name: CASSANDRA_SEED_PROVIDER
        value: org.apache.cassandra.locator.KubernetesSeedProvider
cassandra:
  persistence:
    enabled: true
  image:
    repo: cassandra
    tag: 3.11.8

agent:
  ## Optional Monitoring for Prometheus
  serviceMonitor:
    enabled: false
    additionalLabels: {release:  prometheus}
collector:
  ## Optional Monitoring for Prometheus
  serviceMonitor:
    enabled: false
    additionalLabels: {release:  prometheus}
query:
  ## Optional Monitoring for Prometheus
  serviceMonitor:
    enabled: false
    additionalLabels: {release:  prometheus}
